-- SELECT	ELEC_METER_DATE AS METER_DATE 
-- 		, HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO
-- 		, (ELEC_FOWD_ACCU_EFF - ELEC_REVS_ACCU_EFF) as ELEC_ACTUAL_ACCU_EFF
-- FROM kier.SM_ELEC_METER_HST
-- ORDER BY HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO, ELEC_METER_DATE


-- SELECT	HEAT_METER_DATE AS METER_DATE 
-- 		, HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO
-- 		, HEAT_ACCU_HEAT 
-- FROM kier.SM_HEAT_METER_HST
-- ORDER BY HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO, HEAT_METER_DATE


SELECT	GAS_METER_DATE AS METER_DATE 
		, HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO
		, GAS_ACCU_FLOW
FROM kier.SM_GAS_METER_HST
ORDER BY HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO, GAS_METER_DATE

-- SELECT	HOT_METER_DATE AS METER_DATE 
-- 		, HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO
-- 		, HOT_ACCU_HEAT, HOT_ACCU_FLOW
-- FROM kier.SM_HOT_METER_HST
-- ORDER BY HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO, HOT_METER_DATE

-- SELECT	WATER_METER_DATE AS METER_DATE 
-- 		, HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO
-- 		, WATER_ACCU_FLOW
-- FROM kier.SM_WATER_METER_HST
-- ORDER BY HOUSE_ID_DONG, HOUSE_ID_HO_PRE, HOUSE_ID_HO, WATER_METER_DATE