/* Q
Z 서비스가 2022년 1월에 런칭했습니다.
Z 서비스의 매월 MAU
*/

-- Pass
WITH FIRST_ORD AS (
    SELECT USER_ID, MIN(ORDER_TS) AS DT_FIRST_ORD
    FROM ORDERS AS ORD
    GROUP BY USER_ID
)
, COHORT_ORD AS (
    SELECT  ORD.USER_ID
            , DATE_FORMAT(F_ORD.DT_FIRST_ORD, '%Y-%m-%d') AS COHORT_DATE 
            , DATE_FORMAT(ORD.ORDER_TS, '%Y-%m-%d') AS ORDER_DATE
            , DATEDIFF(ORD.ORDER_TS, F_ORD.DT_FIRST_ORD) AS DAY_DIFF
    FROM ORDERS AS ORD
    LEFT OUTER JOIN FIRST_ORD AS F_ORD ON ORD.USER_ID = F_ORD.USER_ID
)
SELECT COHORT_DATE, DAY_DIFF, COUNT(DISTINCT USER_ID) AS USER_CNT
FROM COHORT_ORD
GROUP BY COHORT_DATE, DAY_DIFF
ORDER BY COHORT_DATE, DAY_DIFF